server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall?zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    # 使用druid数据源
    druid:
      filters: stat
      initialSize: 1
      minIdle: 1
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      useUnfairLock: true
      testWhileIdle: true
      testOnBorrow: false
mybatis:
  type-aliases-package: com.z.mall.**.entity
  mapper-locations: classpath:com/z/mall/**/mapper/*Mapper.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  offset-as-page-num: true
  row-bounds-with-count: true