server:
  port: 80
spring:
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall?zeroDateTimeBehavior=null
    username: root
    password: 123456
    dbcp2:
      initial-size: 0
      min-idle: 1
      max-idle: 20
      max-wait-millis: 60000
mybatis:
  typeAliasesPackage: com.z.mall.**.entity
  mapperLocations: classpath:com/z/mall/**/*Mapper.xml
  basePackage: com.z.mall.**.dao
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  offsetAsPageNum: true
  rowBoundsWithCount: true